### ISSUE TITLE
Help！Help！

### ISSUE THREAD

**Issue by DBook111** [mazurowski-lab/segmentation-guided-diffusion#18]
Hello, I encountered an error while executing: TypeError: UNet2DModel.forward() missing 2 required positional arguments: 'sample' and 'timestep' Can you please tell me the reason for this?
Here is the specific error message:
`running on cuda
output dir: ddim-image-256
using evaluation set: val
Epoch 0:   0%|                                                                                | 0/3 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/image/nvme/ZhouZhiLin/zhouzhilin/Diffusion/duke-anatom-diffusion-generation/main.py", line 424, in <module>
    main(
  File "/home/image/nvme/ZhouZhiLin/zhouzhilin/Diffusion/duke-anatom-diffusion-generation/main.py", line 341, in main
    train_loop(
  File "/home/image/nvme/ZhouZhiLin/zhouzhilin/Diffusion/duke-anatom-diffusion-generation/training.py", line 114, in train_loop
    noise_pred = model(noisy_images, timesteps, return_dict=False)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/image/anaconda3/envs/diffusionOCTA/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/image/anaconda3/envs/diffusionOCTA/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/image/anaconda3/envs/diffusionOCTA/lib/python3.11/site-packages/torch/nn/parallel/data_parallel.py", line 185, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/image/anaconda3/envs/diffusionOCTA/lib/python3.11/site-packages/torch/nn/parallel/data_parallel.py", line 200, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/image/anaconda3/envs/diffusionOCTA/lib/python3.11/site-packages/torch/nn/parallel/parallel_apply.py", line 110, in parallel_apply
    output.reraise()
  File "/home/image/anaconda3/envs/diffusionOCTA/lib/python3.11/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
TypeError: Caught TypeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/image/anaconda3/envs/diffusionOCTA/lib/python3.11/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in _worker
    output = module(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/image/anaconda3/envs/diffusionOCTA/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/image/anaconda3/envs/diffusionOCTA/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UNet2DModel.forward() missing 2 required positional arguments: 'sample' and 'timestep'

Epoch 0:   0%|                                                                                | 0/3 [00:01<?, ?it/s]`

**Comment by nickk124** [comment]
Hi, can you supply the command you used to run the code?

**Comment by DBook111** [comment]
Hello, thank you for your reply. I didn’t run the code in the terminal but used VS Code instead. Initially, I added `os.environ["CUDA_VISIBLE_DEVICES"] = DEVICE` at the beginning of the code, which solved the issue mentioned above.
